spring:
  application:
    name: sj-getway
  redis:
      port: 7000
      host: 47.98.131.216
      password: laosiji123456
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        service-id: pig-config-server
#        enabled: true
#      profile: ${spring.profiles.active}
#      label: ${spring.profiles.active}
#配置日志
logging:
  #配置日志文件路径
  level:
    root: warn
  file: log\gateway.log
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://sj:sj123456@localhost:1025/eureka
    registry-fetch-interval-seconds: 10
zuul:
  ribbon:
    eager-load:
      enabled: false
      clients: sj-system
  ignoredServices: '*'
  host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000


#server:
#  servlet-path: /api
#认证服务器地址
#security:
#  auth:
#    server: http://localhost:8887

security:
  oauth2:
    client:
      client-id: sj
      client-secret: sj
    resource:
      token-info-uri: http://localhost:8887/oauth/check-token
      service-id: sj-getway
      jwt:
         key-uri: http://localhost:8887/oauth/token_key #解析jwt令牌所需要密钥的地址
  validate:
      code: true
ignore:
  urls:
    - /authentication/**
    - /**/*.js
    - /**/*.html
    - /**/*.css
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token
    - /auth/**
    - /system/code/**
    - /system/hashCode/**
#  hashcodeurls:
#    - /system/code/**
# 需要图片验证码的地址
  iamgeurls:
    - /auth/oauth/token
  # 需要短信验证码的地址
  smsurls:
     - /phone/login


server:
  port: 80
